/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    TabBar: typeof import('./../src/components/TabBar.vue')['default']
    UBadge: typeof import('uview-plus/components/u-badge/u-badge.vue')['default']
    UIcon: typeof import('uview-plus/components/u-icon/u-icon.vue')['default']
    USafeBottom: typeof import('uview-plus/components/u-safe-bottom/u-safe-bottom.vue')['default']
    UTabbar: typeof import('uview-plus/components/u-tabbar/u-tabbar.vue')['default']
    UTabbarItem: typeof import('uview-plus/components/u-tabbar-item/u-tabbar-item.vue')['default']
  }
}
