/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    TabBar: typeof import('./../src/components/TabBar.vue')['default']
    VinButton: typeof import('@vingogo/uni-ui/components/button/index.vue')['default']
    VinIcon: typeof import('@vingogo/uni-ui/components/icon/index.vue')['default']
    VinTabbar: typeof import('@vingogo/uni-ui/components/tabbar/index.vue')['default']
    VinTabbarItem: typeof import('@vingogo/uni-ui/components/tabbar-item/index.vue')['default']
  }
}
